DATA = {
    "Bachelor": {
        "Maschinenbau": {
            "pflichtmodule": [
                "elektrotechnik",
                "fertigungslehre",
                "informatik",
                "konstruktionslehre",
                "mathematik_1",
                "mathematik_2",
                "mathematik_3",
                "messtechnik",
                "regelungstechnik",
                "stroemungsmechanik_grundlagen",
                "technische_darstellungslehre",
                "technische_mechanik_1",
                "technische_mechanik_2",
                "technische_mechanik_3",
                "thermodynamik",
                "werkstofftechnik",
            ],
            "vertiefungen": {
                "Entwicklung und Konstruktion": [
                    "antriebstechnik",
                    "dynamik_kraftfahrzeuge",
                    "fahrzeugantriebe",
                    "leichtbau_grundlagen",
                    "maschinendynamik",
                    "nachhaltige_werkstoffauswahl",
                    "projekt_konstruktionslehre",
                    "robotertechnik",
                    "strukturmechanik_fem_1",
                    "werkstofftechnik_2"
                ],
                "Energie- und Umwelttechnik": [
                    "aerodynamik_hydrodynamik",
                    "angewandte_stroemungssimulation",
                    "energietechnik",
                    "grundlagen_stroemungsmaschinen_windturbinen",
                    "kolben_stroemungsmaschinen",
                    "moderne_windenergieanlagen",
                    "regelungssysteme_zustandsraum",
                    "technische_thermodynamik_2",
                    "verbrennungsmotoren_1",
                    "verbrennungsmotoren_2",
                    "waerme_stoffuebertragung"
                ],
                "Produktionstechnik und Logistik": [
                    "antriebssteuerung",
                    "automatisierung_fertigung_montage",
                    "fabrikplanung",
                    "fertigungsmittel",
                    "grundlagen_fuegetechnik",
                    "grundlagen_materialflusstechnik",
                    "logistik",
                    "produktionsplanung_steuerung",
                    "produktionswirtschaft",
                    "robotertechnik"
                ],
                "Regelungstechnik und Mechatronik": [
                    "antriebstechnik",
                    "antriebssteuerung",
                    "automatisierung_fertigung_montage",
                    "digitale_regelung",
                    "komponenten_mechatronischer_systeme",
                    "maschinendynamik",
                    "regelungssysteme_zustandsraum",
                    "robotertechnik"
                ],
                "Schiff- und Meerestechnik": [
                    "einfuehrung_meerestechnik",
                    "grundlagen_hydromechanik_schiffen_offshore",
                    "grundlagen_schiffstechnik",
                    "labor_schiffs_meerestechnik",
                    "schiffs_offshorekonstruktionen"
                ],
                "Sustainable Engineering": [
                    "aerodynamik_hydrodynamik",
                    "antriebstechnik",
                    "einfuehrung_meerestechnik",
                    "energietechnik",
                    "grundlagen_schiffstechnik",
                    "grundlagen_stroemungsmaschinen_windturbinen",
                    "klimaneutrale_kraftstoffe",
                    "leichtbau_grundlagen",
                    "logistik",
                    "moderne_windenergieanlagen",
                    "nachhaltige_werkstoffauswahl",
                    "technische_thermodynamik_2"
                ]
            },
            "sonstige_wahlmodule": [
                "projekt_additive_fertigung",
                "projekt_antriebssysteme_embedded_systems",
                "technische_dokumentation"
            ],
            "nichttechnischer_wahlpflichtbereich":[
                "einfuehrung_cpp",
                "englisch_fachkommunikation_maschinenbau_c11",
                "gewerbliche_schutzrechte",
                "englisch_fachkommunikation_ing_c12",
                "management_entwicklungsteams_projekten",
                "numerik_stochastik_ing",
                "balance",
            ],
            
        },

        "Mechatronik": {
            "pflichtmodule": [
                "elektrotechnik_1",
                "elektrotechnik_2",
                "elektrotechnik_3",
                "fertigungslehre",
                "informatik",
                "konstruktionslehre",
                "mathematik_1",
                "mathematik_2",
                "mathematik_3",
                "messtechnik",
                "regelungstechnik",
                "stroemungsmechanik_grundlagen",
                "technische_darstellungslehre",
                "technische_mechanik_1",
                "technische_mechanik_2",
                "technische_mechanik_3",
                "thermodynamik",
                "werkstofftechnik",
            ],
            "technischer_wahlpflichtbereich": [
                "dynamik_kraftfahrzeuge",
                "echtzeitsysteme",
                "komponenten_mechatronischer_systeme",
                "messtechnik_analoge_schaltungen",
                "robotertechnik",
                "thermodynamik",
                "werkstofftechnik",
                "antriebssteuerung",
                "antriebstechnik",
                "elektrische_fahrzeugantriebe",
                "fahrzeugantriebe",
                "grundlagen_automatisierung",
                "grundlagen_elektronik",
                "grundlagen_stroemungsmaschinen_windturbinen",
                "maschinendynamik",
                "mikrosystemtechnologie",
                "modellbildung_simulation_technischer_systeme",
                "rechnetgestützter_reglerentwurf",
                "sensorik",
                "signal_systemtheorie",
                "strukturmechanik_fem_1",
                "technische_optik",
                "technische_thermodynamik_2",
                "waerme_stoffuebertragung"
            ],
            "nichttechnische_wahlmodule": [
                "computerorientierte_mathematik_algorithmen_strukturen",
                "englisch_fachkommunikation_el_technik_info_c11",
                "englisch_fachkommunikation_maschinenbau_c11",
                "englisch_fachkommunikation_ing_c12",
                "management_entwicklungsteams_projekten",
                "informatik_wissenschaft_gesellschaft",
                "deskriptive_statistik",
            ],
        },

        "Biomedizinische Technik": {
            "pflichtmodule": [
                "anatomie_und_physiologie",
                "biomaterialieneinsatz_und_prüfung",
                "biomedizinische_technik",
                "elektrotechnik",
                "grundlagen_chemie",
                "informatik",
                "konstruktionslehre",
                "mathematik_1",
                "mathematik_2",
                "mathematik_3",
                "medizinische_grundlagen",
                "messtechnik",
                "nichtmetallische_werkstoffe",
                "regelungstechnik",
                "stroemungsmechanik_grundlagen",
                "technische_darstellungslehre",
                "technische_mechanik_1",
                "technische_mechanik_2",
                "technische_mechanik_3",
                "thermodynamik",
                "werkstofftechnik",
            ],
            "technischer_wahlpflichtbereich": [
                "aerodynamik_hydrodynamik",
                "angewandte_stroemungssimulation",
                "digitale_regelung",
                "fertigungslehre",
                "leichtbau_grundlagen",
                "maschinendynamik",
                "projekt_additive_fertigung",
                "regelungssysteme_zustandsraum",
                "strukturmechanik_fem_1",
                "technische_dokumentation",
                "waerme_stoffuebertragung",
            ],
            "nichttechnischer_wahlpflichtbereich": [
                "balance",
                "einfuehrung_betriebswirtschaftslehre",
                "einfuehrung_cpp",
                "englisch_fachkommunikation_ing_c12",
                "englisch_fachkommunikation_maschinenbau_c11",
                "gewerbliche_schutzrechte",
                "grundlagen_materiner_stoffkreislaeufe",
                "management_entwicklungsteams_projekten",
                "moderne_physik_ingenieurwissenschaften",
                "numerik_stochastik_ing",
                "strategisches_marketing"
            ],
        },

        "Wirtschaftsingenieurwesen": {
            "pflichtmodule": [
                "einfuehrung_betriebswirtschaftslehre",
                "einfuehrung_wirtschaftsrecht",
                "elektrotechnik",
                "fertigungslehre",
                "finanzbuchhaltung",
                "finanzierung_investition",
                "grundlagen_statistik",
                "informatik",
                "konstruktionslehre",
                "kosten_leistungsrechnung",
                "mathematik_1",
                "mathematik_2",
                "mathematik_3",
                "personlawirtschaftslehre_organisationen",
                "produktionsplanung_steuerung",
                "technische_darstellungslehre",
                "technische_mechanik_1",
                "technische_mechanik_2",
                "technische_mechanik_3",
                "werkstofftechnik"
            ],
            "technischer_wahlpflichtbereich": [
                "automatisierung_fertigung_montage",
                "energietechnik",
                "grundlagen_fuegetechnik",
                "grundlagen_materialflusstechnik",
                "leichtbau_grundlagen",
                "messtechnik",
                "robotertechnik",
                "technische_dokumentation",
                "thermodynamik",
                "gewaesserregelung_kuesten_hochwasserschutz",
                "verbrennungsmotoren_1",
                "balance",
                "fabrikplanung",
                "fertigungsmittel",
                "grundlagen_schiffstechnik",
                "grundlagen_stroemungsmaschinen_windturbinen",
                "stroemungsmechanik_grundlagen",
                "regelungstechnik",
                "technische_thermodynamik_2",
                "verbrennungsmotoren_2",
                "waerme_stoffuebertragung",
                "werkstofftechnik_2",
                "umweltverfahrenstechnik",
            ],
            "wahlpflichtbereich_wirtschaftswissenschaften": [
                "einfuehrung_betriebswirtschaftsliche_steuerlehre",
                "erfolgsfaktoren_beruflicher_selbstaendigkeit",
                "finanzierung_investition_2",
                "grundlagen_bevölkerungsökonomik",
                "grundlagen_controlling",
                "grundzüge_dienstleistungsmanagement",
                "grundzüge_moderner_oekonomie",
                "ideenfindung_entwicklung",
                "strategisches_marketing"
            ],
        }
    },

    "Master": {
        "Maschinenbau": {
            "vertiefungen": {
                "Antriebstechnik": [
                    "aktive_systeme_kraftfahrzeug",
                    "alternative_antriebssysteme",
                    "entwerfen_antriebe",
                    "hydraulik_pneumatik",
                    "regelungsorientierte_modellbildung_mechatronik",
                    "technische_schwingungslehre",
                    "verbrennungsmotoren_4"
                ],
                "Fertigungstechnik": [
                    "additive_fertigungsverfahren",
                    "anlagenwirtschaft",
                    "fertigungsmittel",
                    "klebtechnik",
                    "qualitaetsmanagement",
                    "schiffsfertigungstechnik"
                ],
                "Konstruktionstechnik": [
                    "additive_fertigungsverfahren",
                    "betriebsfestigkeit",
                    "cad",
                    "experimenteller_leichtbau",
                    "konstruktionsmethodik",
                    "projekt_produktentwicklung",
                    "strukturmechanik_fem_2"
                ],
                "Leichtbau": [
                    "betriebsfestigkeit",
                    "biomaterialien_maschinenbau",
                    "experimenteller_leichtbau",
                    "festigkeitsoptimiertes_gestalten",
                    "klebtechnik",
                    "leichtbaukonstruktion",
                    "leichtbauwerkstoffe",
                    "metallische_konstruktionswerkstoffe",
                    "strukturmechanik_fem_2"
                ],
                "Logistik": [
                    "ausgewaehlte_themen_logistik",
                    "cad",
                    "intralogistik",
                    "leichtbaukonstruktion",
                    "maritime_logistik",
                    "supply_chain_management"
                ],
                "Mechatronik": [
                    "aktive_systeme_kraftfahrzeug",
                    "dynamik_mehrkoerpersysteme",
                    "nichtlineare_regelungssysteme",
                    "optimierungsmethoden_mechatronik",
                    "regelungsorientierte_modellbildung_mechatronik",
                    "robuste_regelung",
                    "technische_schwingungslehre"
                ],
                "Schweißtechnik": [
                    "betriebsfestigkeit",
                    "metallische_konstruktionswerkstoffe",
                    "qualitaetsmanagement",
                    "schiffsfertigungstechnik",
                    "schweisskonstruktion",
                    "schweissmetallurgie",
                    "schweisstechnologie",
                    "umformtechnisches_fuegen"
                ],
                "Strömungsmaschinen": [
                    "betriebsfestigkeit",
                    "grundlagen_akustik",
                    "hydraulische_stroemungsmaschinen",
                    "labor_thermische_maschinen",
                    "leichtbauwerkstoffe",
                    "numerische_stroemungsmechanik",
                    "technische_schwingungslehre",
                    "thermische_stroemungsmaschinen",
                    "windenergie_simulation"
                ],
                "Strömungsmechanik und Aerodynamik": [
                    "angewandte_stroemungsmechanik",
                    "experimentelle_stroemungsmechanik",
                    "hydraulische_stroemungsmaschinen",
                    "labor_thermische_maschinen",
                    "leichtbaukonstruktion",
                    "mikrofluidik",
                    "nichtnewtonsche_fluidmechanik",
                    "numerische_stroemungsmechanik",
                    "thermische_stroemungsmaschinen",
                    "turbulenzmodellierung"
                ],
                "Strukturmechanik": [
                    "betriebsfestigkeit",
                    "dynamik_mehrkoerpersysteme",
                    "elastische_mehrkoerpersysteme",
                    "ermuedungsrisse",
                    "festigkeitsoptimiertes_gestalten",
                    "metallische_konstruktionswerkstoffe",
                    "strukturmechanik_fem_2",
                    "technische_schwingungslehre"
                ],
                "Thermische Maschinen/Verbrennungsmotoren": [
                    "aufladung_verbrennungsmotor",
                    "grossmotoren_schiff",
                    "hydraulische_stroemungsmaschinen",
                    "kraft_schmierstoffe_co2",
                    "labor_thermische_maschinen",
                    "mehrstoffthermodynamik",
                    "motor_energiemanagement",
                    "thermische_stroemungsmaschinen",
                    "thermodynamik_verbrennung",
                    "verbrennungsmotoren_3",
                    "verbrennungsmotoren_4"
                ],
                "Thermische Prozesse/Energieanlagen": [
                    "kaelte_klimatechnik",
                    "labor_thermische_maschinen",
                    "mehrstoffthermodynamik",
                    "modellierung_turbulenz",
                    "motorthermodynamik",
                    "numerische_stroemungsmechanik",
                    "regenerative_energietechnik",
                    "thermodynamik_umweltprozesse",
                    "thermodynamik_verbrennung",
                    "verbrennungsmotoren_3"
                ],
                "Werkstofftechnik": [
                    "additive_fertigungsverfahren",
                    "biomaterialien_maschinenbau",
                    "festigkeitsoptimiertes_gestalten",
                    "labor_werkstofftechnik",
                    "leichtbauwerkstoffe",
                    "metallische_konstruktionswerkstoffe",
                    "nanomaterialien",
                    "nichtmetallische_werkstoffe",
                    "simulation_werkstofftechnik",
                    "werkstoffanalytik"
                ],
                "Windenergietechnik": [
                    "betriebsfestigkeit",
                    "dynamik_mehrkoerpersysteme",
                    "elastische_mehrkoerpersysteme",
                    "grundlagen_akustik",
                    "konstruktion_windenergieanlagen",
                    "leichtbaukonstruktion",
                    "numerische_stroemungsmechanik",
                    "regelungsorientierte_modellbildung_mechatronik",
                    "theorie_offshore_systeme",
                    "windenergietechnik"
                ],               
            },
           "sonstige_wahlmodule": [
                "modellierung_abgasnachbehandlung",
                "schadensanalyse_sicherheitsrelevanter_produkte",
                "technologien_meeresenergienutzung"
            ],
            "nichttechnischer_wahlpflichtbereich":[
                "einfuehrung_cpp",
                "englisch_fachkommunikation_maschinenbau_c11",
                "gewerbliche_schutzrechte",
                "englisch_fachkommunikation_ing_c12",
                "management_entwicklungsteams_projekten",
                "numerik_stochastik_ing",
                "balance",
                "management_entwicklungsteams_projekten",
            ],
        },

        "Mechatronik": {
            "wahlpflichtbereich": {
                "Mathematische und Physikalische Grundlagen": [
                    "compact_modeling_large_scale_dynamical_system",
                    "digitale_signalverarbeitung",
                    "dynamik_mehrkoerpersysteme",
                    "elastische_mehrkoerpersysteme",
                    "grundlagen_akustik",
                    "modeling_symulation_mechatronic_systems",
                    "technische_schwingungslehre",
                ],

                "Regelungstechnik": [
                    "ausgewaehlte_anwendung_regelungstechnik",
                    "moderne_methoden_regelungstechnik",
                    "nichtlineare_regelungssysteme",
                    "optimierungsmethoden_mechatronik",
                    "regelungsorientierte_modellbildung_mechatronik",
                    "robuste_regelung_zustandsschaetzung",
                ],

                "Komponenten mechatronischer Systeme": [
                    "dynamic_behavior_ac_mashine",
                    "fortgeschrittene_elektronik_schaltkreisentwurf",
                    "geregelte_elektrische_antriebe",
                    "hydraulik_pneumatik",
                    "leistungshalbleiter",
                    "maritime_sensorik",
                    "prozessautomation_robotik",
                    "umrichterregelung_erneubare_energien",
                ],

                "Integration und Erprobung mechatronischer Systeme": [
                    "eingebettete_multi_prozessor_systeme",
                    "fehlerdiagnose_und_fehlertoleranz_in_technischen_systemen",
                    "geraetetechnik",
                    "konstruktionsmethodik",
                    "leichtbaukonstruktion",
                    "projekt_produktentwicklung",
                    "qualitaetsmanagement",
                    "verteilte_eingebettete_systeme",
                    "zuverlaessigkeit_und_testbarkeit_elektronischer_systeme",
                ],

                "Anwendung": [
                    "additive_fertigungsverfahren",
                    "aktive_systeme_kraftfahrzeug",
                    "alternative_antriebssysteme",
                    "entwerfen_antriebe",
                    "mikrofluidik",
                    "mikrotechnologie_aktore_sensoren",
                    "modellierung_abgasnachbehandlung",
                    "motor_energiemanagement",
                    "motorthermodynamik",
                    "project_seminar_power_electronics",
                    "renewable_energy_sources",
                ],
        
            },
            "ergaenzender_wahlbereich":[
                    "englisch_fachkommunikation_ing_c12",
                    "englisch_fachkommunikation_maschinenbau_c11",
                    "gewerbliche_schutzrechte",
                    "management_entwicklungsteams_projekten"
            ],
        },

        "Biomedizinische Technik": {
            "pflichtmodule": [
                "ausgewaehlte_kapitel_der_biomedizinischen_technik",
                "geraetetechnik_und_sensorik_in_der_biomedizinischen_technik",
                "endoprothetik_und_orthopaedische_chirurgie",
                "numerik_fuer_ingenieurwissenschaften",
                "polymere_als_biomaterialien",
                "angewandte_biomechanik",
                "ip_management_in_der_medizintechnik",
                "medizinische_technologie_bildgebende_verfahren"
            ],
            "technischer_wahlpflichtbereich": [
                "additive_fertigungsverfahren",
                "dynamik_mehrkoerpersysteme",
                "ermuedungsrisse",
                "festigkeitsoptimiertes_bruchsicheres",
                "grundlagen_angewandten_muskuloskelettalen_biomechanik_orthopaedietechnik",
                "nanomaterialien",
                "implantattechnologie",
                "nichtlineare_regelungssysteme",
                "nichtnewtonsche_fluidmechanik",
                "numerische_stroemungsmechanik",
                "regelungsorientierte_modellbildung_mechatronik",
                "schadensanalyse_sicherheitsrelevanter_produkte",
                "strukturmechanik_fem_2",
                "angewandte_biofluidmechanik_medizintechnik",
                "betriebsfestigkeit",
                "open_space",
                "cad",
                "elastische_mehrkoerpersysteme",
                "kardiovakulaere_implantate",
                "mikrofluidik",
                "stochastik",
                "technische_schwingungslehre",
                "werkstofftechnik_2",
            ],
            "nichttechnischer_wahlpflichtbereich":[
                "einfuehrung_cpp",
                "englisch_fachkommunikation_maschinenbau_c11",
                "gewerbliche_schutzrechte",
                "englisch_fachkommunikation_ing_c12",
                "management_entwicklungsteams_projekten",
                "numerik_stochastik_ing",
                "balance",
            ],

        },

        "Wirtschaftsingenieurwesen": {
            "pflichtmodule": [
                "dienstleistungsmarketing",
                "unternehmensrechnung_controlling_finanzierung",
            ],
            "ingenieurwissenschaftliche_vertiefung": {
                "Automatisierungstechnik":[
                    "ausgewaehlte_anwendung_regelungstechnik",
                    "fehlerdiagnose_und_fehlertoleranz_in_technischen_systemen",
                    "geregelte_elektrische_antriebe",
                    "mikrotechnologie_aktore_sensoren",
                    "modeling_symulation_mechatronic_systems",
                    "moderne_methoden_regelungstechnik",
                    "optimierungsmethoden_mechatronik",
                    "prozessautomation_robotik",
                    "projektseminar_entwurf_simulation_elektronischer_baugruppen",
                    "prozessmesstechnik",
                    "robust_control",
                    "technische_optik",
                    "zuverlaessigkeit_und_testbarkeit_elektronischer_systeme",
                ],
                "Elektrische Energietechnik":[
                    "ausgewaehlte_anwendung_regelungstechnik",
                    "geregelte_elektrische_antriebe",
                    "hochtemperaturelektronik",
                    "leistungshalbleiter",
                    "moderne_methoden_regelungstechnik",
                    "power_system_control_protection",
                    "power_system_dynamic_stability_control",
                    "project_seminar_power_electronics",
                    "projektseminar_entwurf_simulation_elektronischer_baugruppen",
                    "prozessautomation_robotik",
                    "renewable_energy_grid_connection_controller_design_grid_code_requirements",
                    "umrichterregelung_erneubare_energien",
                    "zuverlaessigkeit_und_testbarkeit_elektronischer_systeme",
                ],
                "Informationstechnologie":[
                    "advanced_cpu_design",
                    "bild_videoverarbeitung_und_codierung",
                    "data_driven_methods_in_signal_processing",
                    "digitale_datenuebertragung",
                    "kanalcodierung",
                    "mobilkommunikation",
                    "radio_navigation_and_radar",
                    "rechnerarchitekturen_fuer_deep_learning_anwendungen",
                ],
                "Energie- und Umwelttechnik":[
                    "hydraulische_stroemungsmaschinen",
                    "kaelte_klimatechnik",
                    "klimaneutrale_kraftstoffe",
                    "mehrstoffthermodynamik",
                    "motorthermodynamik",
                    "regenerative_energietechnik",
                    "windenergie_simulation",
                    "thermische_stroemungsmaschinen",
                    "verbrennungsmotoren_1",
                    "verbrennungsmotoren_2",
                    "waerme_stoffuebertragung",
                    "windenergietechnik"
                ],
                "Fertigungs- und Automatisierungstechnik":[
                    "additive_fertigungsverfahren",
                    "anlagenwirtschaft",
                    "ausgewaehlte_fertigungsverfahren",
                    "automobile_produktion",
                    "digitale_regelung",
                    "klebtechnik",
                    "metallische_konstruktionswerkstoffe",
                    "moderne_methoden_regelungstechnik",
                    "optimierungsmethoden_mechatronik",
                    "qualitaetsmanagement",
                    "schiffsfertigungstechnik",
                    "schweisskonstruktion",
                    "schweissmetallurgie",
                    "schweisstechnologie",
                    "steuerungstechnik",
                    "umformtechnisches_fuegen"
                ],
                "Logistik":[
                    "anlagenwirtschaft",
                    "ausgewaehlte_themen_logistik",
                    "automobile_produktion",
                    "industrial_engineering",
                    "management_entwicklungsteams_projekten",
                    "maritime_logistik",
                    "steuerungstechnik",
                    "supply_chain_management",
                    "vernetzte_produktion_und_logistik",
                ],
                "Produktentwicklung":[
                    "additive_fertigungsverfahren",
                    "advanced_analysis_of_marine_structures",
                    "cad",
                    "festigkeitsoptimiertes_bruchsicheres",
                    "konstruktionsmethodik",
                    "leichtbaukonstruktion",
                    "leichtbauwerkstoffe",
                    "management_entwicklungsteams_projekten",
                    "metallische_konstruktionswerkstoffe",
                    "principle_analysis_of_marine_structures",
                    "projekt_produktentwicklung",
                    "structural_durability",
                    "technische_schwingungslehre",
                ],
            },
            "wirtschaftswissenschaftlicher_wahlpflichtbereich": [
                # WiWi-Module
            ],
            "ergaenzender_wahlpflichtbereich": [
                # ergänzende Module
            ],
            "sonstige_wahlmodule": [
                "balance",
                "design_underwater_systems",
                "englisch_fachkommunikation_ing_c12",
                "englisch_fachkommunikation_maschinenbau_c11",
                "englisch_fachkommunikation_wiwi_c11",
                "englisch_fachkommunikation_wiwi_c12",
                "grossmotoren_schiff",
                "introduction_applied_programming_cpp",
                "mikrofluidik",
                "motor_energiemanagement",
                "ocean_renewable_energies",
                "optimierungsmethoden_mechatronik",
                "verbrennungsmotoren_3",
                "verbrennungsmotoren_4",
                
            ],
        },

        "Sustainable Engineering": {
            "pflichtmodule": [
                "design_offshore_systems",
                "principle_analysis_of_marine_structures",
                "principles_of_marine_fluid_mechanics",
                "safety_maritime_systems",
                "ship_design"
            ],
            "wahlmodule": [
                "advanced_analysis_of_marine_structures",
                "advanced_analysis_offshore_systems",
                "cfd_maritime_engineering",
                "coding_of_finite_elements",
                "composite_material_design",
                "continuum_mechanics",
                "deep_sea_technology_underwater_applications",
                "design_offshore_aquaculture_systems",
                "design_underwater_systems",
                "experimental_methods_maritime_engineering",
                "large_engines_energy_converters_fuels",
                "modelling_turbulent_flows",
                "navigation_control_autonomy_systems",
                "ocean_renewable_energies",
                "ocean_research_technologies",
                "ocean_waves",
                "resistance_propulsion",
                "sailing_theory",
                "seakeeping_manoeuvring",
                "selected_topics_for_the_analysis_of_marine_structures",
                "ship_life_cycle_digitalization",
                "structural_design_marine_structures",
                "technical_production_processes_ships",
                "ultimate_strength_assessment_of_marine_structures"
            ],
            "sonstige_wahlmodule":[
                "dynamics_multibody_systems",
                "finite_element_analysis_composite_structures",
                "introduction_applied_programming_cpp",
                "introduction_data_science_materials",
                "maritime_graphics",
                "metallic_engineering_materials",
                "numerical_and_experimental_hydroacoustics",
                "numerical_fluid_mechanics_turbulent_flows",
                "principles_of_energy_technology_systems_and_applications_in_maritime_context",
                "robust_control",
                "structural_durability",
                "technical_fluids_sustainable_maritime"
            ],
            "nichttechnischer_wahlpflichtbereich": [
                "deutsch_a11",
                "deutsch_a12",
                "englisch_fachkommunikation_ing_c12",
                "englisch_fachkommunikation_maschinenbau_c11",
                "essentials_ocean_science_and_sustainable_ocean_use",
                "reasoning_under_uncertainty"
            ]
        }
    }
}